### ISSUE TITLE
Uploading in 'High Quality'

### ISSUE THREAD

**Issue by jawadkho** [google/java-photoslibrary#1]
Does this allow us to upload photos/videos in Google Photo's 'high quality' as opposed to the original quality?

****

**Comment by jfschmakeit** [comment]
This is not currently supported as part of the Google Photos Library API. There's a feature request open on the issue tracker for the Library API, please 'star' it there to be notified of any updates: https://issuetracker.google.com/111193036

(This feature request is not specific to just the Java client library, but the Google Photos Library API, I'll close it here.)
