### ISSUE TITLE
Min SDK version?

### ISSUE THREAD

**Issue by panovvitalik** [google/java-photoslibrary#11]
Is there a way to support api's lower than SDK 24?

For example methods: 
UploadMediaItemResponse.getError().isPresent()
UploadMediaItemResponse.getUploadToken().get()
These calls need min SDK version: 24

Can it support for example sdk 23 or lower?

**Comment by jfschmakeit** [comment]
This library currently requires Java 8 (which is only available on Android API level 24 or higher). 

However, I don't believe the Java 8 functionality is critical to the library and we might be able to rewrite those parts for Java 7 (which would give us support for a lower minSDK for Android).

Let's track this here, but pull requests are welcome too. :smiley:
