### ISSUE TITLE
Can do set thumbnail when upload video ?

### ISSUE THREAD

**Issue by hoangdangduy** [google/java-photoslibrary#12]
I don't find any document about set thumbnail when upload video.
If have document or code about that, please provide it or show for me.
Thanks so much.

**Comment by jfschmakeit** [comment]
The thumbnail is automatically generated from the video file. The Google Photos Library API does not support setting a custom thumbnail for a video.

You could file a feature request for the API, outlining your exact use case and how you would like to use it. More details here: https://developers.google.com/photos/library/support/how-to-get-help#bugs-feature
