### ISSUE TITLE
How to request only specified fields in API reponses ?

### ISSUE THREAD

**Issue by bubbleguuum** [google/java-photoslibrary#13]
I want some requests to only return certain fields as explained here:

https://developers.google.com/photos/library/guides/performance-tips

How is it done with this API ?

**Comment by jfschmakeit** [comment]
Unfortunately this feature is only supported by the HTTP REST endpoint and not this client library.

It is not possible to restrict the fields that are returned by the client library due to the underlying network architecture and how calls to the API are made.

**Comment by bubbleguuum** [comment]
Thank you for letting me know. Not a huge deal but it would be great to have this functionality added if it provides a significant improvement in loading and processing times.
