### ISSUE TITLE
How to grant permission access data don't need confirm on web interface when run on server command?

### ISSUE THREAD

**Issue by hoangdangduy** [google/java-photoslibrary#14]
@jfschmakeit  When I run my application on Window OS I will can interact with UI to grant permission but I want run it on server only have command. Do you have way to by pass it ? 
Thanks!

![QA1](https://user-images.githubusercontent.com/8912039/54451813-46c4c080-4786-11e9-8992-6f17363ec0ae.png)
![QA2](https://user-images.githubusercontent.com/8912039/54451814-46c4c080-4786-11e9-81d5-3ea210991369.png)

**Comment by jfschmakeit** [comment]
The Google Photos Library API requires user OAuth credentials. Service accounts or other non-interactive credenials are not supported. You can find more details on the [Authentication and Authorization page in the developer documentation](https://developers.google.com/photos/library/guides/authentication-authorization#what-scopes).

The only way to obtain these credentials is to prompt the user via a URL to authorize access.
