### ISSUE TITLE
No route to host: photoslibrary.googleapis.com/2607

### ISSUE THREAD

**Issue by wmcalyj** [google/java-photoslibrary#16]
I am able to run my application locally.
But after running for 20-30 minutes, I received an exception saying "Exception in thread "main" com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
" and the root cause is "No route to host: photoslibrary.googleapis.com/2607"

Any idea what's causing the issue and how this can be avoided?

Thanks in advance.

**Comment by jfschmakeit** [comment]
This sounds like a platform issue on your system. Can you still reach photoslibrary.googleapis.com when this error occurs? (e.g. can you still `ping hotoslibrary.googleapis.com`?) It looks like your system has lost network access?

Can you fix this issue by restarting your application or your device?
