### ISSUE TITLE
No way to add photos to an existing album

### ISSUE THREAD

**Issue by Serginho** [google/java-photoslibrary#18]
>Exception in thread "main" com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No permission to add media items to this album.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)

There isn't any scope which allows us to do this. It's a pain in the ass because there is no way to organize photos into existing albums.

**Comment by jfschmakeit** [comment]
Adding photos to existing albums is not supported by the Google Photos Library API.

There is a similar feature request on the API issue tracker here: https://issuetracker.google.com/110692941

You can 'star' this request to draw attention to it and be notified of any updates.
