### ISSUE TITLE
Question: Is it possible to get all photos and their coordinates on the world?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/java-photoslibrary#21]
This could be useful for showing a world/local map with all the photos...

**Comment by jfschmakeit** [comment]
Getting the location of photos is not supported through the Google Photos Library API.
It looks like you have already opened an issue on the issue tracker for the API to track this further: https://issuetracker.google.com/134692577

**Comment by AndroidDeveloperLB** [comment]
Yes I wrote both.
Here I wrote in case it is actually possible, and there I wrote in case it's not.
And later I've found out that there is a similar request anyway.
I've noticed that even if developers wish to use a workaround of Drive sync, it won't be possible:
https://www.androidpolice.com/2019/06/12/google-drive-photos-sync/
That's why I thought it would be nice to have this.
