### ISSUE TITLE
Does the java-photoslibrary provide api for function recovery storage ?

### ISSUE THREAD

**Issue by hoangdangduy** [google/java-photoslibrary#27]
I upload more file photo and video to my account google photo and come quickly full storage so I must manualy run  function recovery storage to renew my storage.
Whether java-photoslibrary can add api to do it ?
Thanks!

[https://photos.google.com/settings](url)
![recover storage](https://user-images.githubusercontent.com/8912039/71309074-338e0200-2436-11ea-9bc8-68b1e6884071.png)

**Comment by jfschmakeit** [comment]
This is not a feature that is available through the Google Photos Library API. You can check [the documentation here](https://developers.google.com/photos) to see what features are supported.
