### ISSUE TITLE
video duration

### ISSUE THREAD

**Issue by tao1** [google/java-photoslibrary#3]
Hello,

I can't find how to get video duration in API. Any clue ?

Kind regards,

Laurent

**Comment by jfschmakeit** [comment]
The Google Photos library API does not return the duration of a video, but this sounds like a useful addition.

Could you please file a feature request on the API itself and outline how you would use this functionality? See the [support page](https://developers.google.com/photos/library/support/how-to-get-help#bugs-feature) in the developer documentation on how to file an issue against the API.

Thanks!

**Comment by tao1** [comment]
https://issuetracker.google.com/issues/123979425

**Comment by bubbleguuum** [comment]
I'd really like to have this as well. It was available in the old Picasa Web API.
