### ISSUE TITLE
Impossible to interrupt a long-running media item upload

### ISSUE THREAD

**Issue by ylexus** [google/java-photoslibrary#30]
`PhotosLibraryClient.uploadMediaItem()` is blocking uninterruptibly until the upload is complete. In a UI app it means the user is unable to cancel the upload process without killing the app.

<img width="513" alt="Screenshot 2020-04-25 at 23 38 50" src="https://user-images.githubusercontent.com/6009806/80292330-f1f7c580-874d-11ea-8c28-30588675e0c8.png">

Related to https://github.com/ylexus/jiotty-photos-uploader/issues/23

**Comment by ylexus** [comment]
Any chance this can be improved?

**Comment by jfschmakeit** [comment]
We are currently working on some major improvements to the upload flow in the client library - in particular around retries and error handling. This sounds like something that should be considered as well. 

You can also configure a timeout for upload calls that cancels any in-progress requests. 

(Ideally, calling `.cancel(..)` on the `ApiFuture` returned by making a call through the `PhotosLibraryClient#uploadMediaItemCallable()` should interrupt and cancel the upload. This is something we are looking at improving.)

**Comment by jfschmakeit** [comment]
The behaviour around this has been improved in the latest release (1.7.0): https://github.com/google/java-photoslibrary/releases/tag/v1.7.0

You should now be able to cancel (and interrupt) long running media uploads. Please file a new issue if you are having issues with this behaviour after upgrading to the latest version.
