### ISSUE TITLE
Base urls expire before 60 minutes

### ISSUE THREAD

**Issue by rowanalex123** [google/java-photoslibrary#38]
The Photos API docs indicate the direct media links/base urls [expire in 60 minutes](https://developers.google.com/photos/library/guides/access-media-items#base-urls). But the links seem to expire within 40 mins in some cases, return a 4xx when accessed.

**Comment by rowanalex123** [comment]
Example: this [base url](https://lh3.googleusercontent.com/lr/AFBm1_YU2JeoWYdxLzXLHp_Q5sIgRJEMG1V2d-rC9-6s03XRR5bGsJCzUvSSanXPf3osaSN9gTnj10dEeXChPxau-w4bJQSBmjtiCUdeAGfGmlVidOkzEZ3e3-mO7vIGPr1_TJJE9k-ZueuhIExXsvXv6l7MaFAvvUscxQHa5dyakVhAbs67sJARzPKpPcNC-6zVmdZLpAxkL_sMsGbMu2BZtkwT3rha2ajpYSI8qHFaO21P68Gwl17YDGeXwxbEdkRbcHxY6pshVscUTqusSeVNhAUIhCpihRqBK7aUAaf8F-NNko7nLRAcE1Ithc-DjEcEYd5qY-ei0WryYp0pN1f6xs9z5TJWfvBFbM5imulF64cJcffkskEcAuGgSMvDQ4fxLfqrzesk6Cc3d1mSStGpiQq5Jbfx-RUDPKihVGcj_s9LB5kTB1ETppZg63I-hPMIX4vxcVOkKuayoQcReVeu7E4NqOdhH-ofNALbXcKuTjRJzYkxviocFFhd89cThZl_SOUxpj1aW-zDqNUcrXOMwJaIBFednw-rMaH7hk5zG6WGCT45rVmz-VxxRF61mMyslpvewMpOO97qhWuf_4e-IVVtRlxBgSVNl4j7k-yzQA1DcO6H-S_-vAu7sDxtt8Z9U7KlamJdpO2YU95ROMhJ2CmUwz0ATvAPZ7GkkLttJVcnzdAuSJFth4AHAk-nibnn75A_0SRf4gkxDajeLBHYtBDtwsufgxtJWkZekjt37hyEsghEzgvuEHjV52KukSxcvymecwnmwP5cXFbr9pv9TQ0Tbe10npWI4xSCJCnTaqSV4beQP1WWjGU2QeClYojq=w1920-h1080) returns a 403 after 30 mins.

**Comment by rowanalex123** [comment]
Posted the issue here - https://issuetracker.google.com/issues/165028980

**Comment by jfschmakeit** [comment]
We are tracking this issue in the Library API issue tracker - https://issuetracker.google.com/issues/165028980
