### ISSUE TITLE
Process upload still hold file after upload success

### ISSUE THREAD

**Issue by hoangdangduy** [google/java-photoslibrary#8]
I create application run 24/24. Then file was uploaded success, I want to delete file but it still was holded by process upload lead to an exception was throw. So, how the way to delete file when upload success and java application still run ?

My code upload is below.

![qa google photo client java 3](https://user-images.githubusercontent.com/8912039/52659744-a2562100-2f30-11e9-8fbd-71a90466130c.png)

**Comment by jfschmakeit** [comment]
You will need to explicitly call `close()` on the `RandomAccessFile` that you have created for the upload request. The best place to do this would be the `UploadMediaItemResponse` has been returned.  This library does not handle the opening or closing of files, that's up to the developer to handle correctly. 
(For example, you may wish to retry the call with the same file, without closing it first.)

It looks like the code sample in the documentation isn't quite showing this - I have filed a bug internally to improve this.
