### ISSUE TITLE
No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

### ISSUE THREAD

**Issue by panovvitalik** [google/java-photoslibrary#9]
Added:
implementation 'com.google.photos.library:google-photos-library-client:1.1.0'

Trying to exexecute this code:
PhotosLibrarySettings settings =
                    PhotosLibrarySettings.newBuilder()
                            .setCredentialsProvider(
                                    FixedCredentialsProvider.create(UserCredentials.newBuilder()
                                            .setClientId(GOOGLE_CLIENT_ID)
                                            .setClientSecret(GOOGLE_CLIENT_SECRET)
                                            .setAccessToken(new AccessToken("my access token", null))
                                            .build()))
                            .build();

            PhotosLibraryClient photosLibraryClient =
                    PhotosLibraryClient.initialize(settings); 

Getting this error:
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

Please help. What should I do to fix this issue

**Comment by panovvitalik** [comment]
I was cut off using of this "shi..." library from my project.
And reimplemented all work with direct REST calls. "Thank you"

So question is not actual.

**Comment by wmcalyj** [comment]
I have the same issue and cannot find any workaround.
Any idea how this can be solved?

**Comment by panovvitalik** [comment]
> I have the same issue and cannot find any workaround.
> Any idea how this can be solved?
I fixed it like this way, pls see code below:
BUT! many fllowing issues I can not resolve, here is no supporting :( . 
And I advice to reimplement Your code to direct REST calls - I already did it.

implementation ('io.grpc:grpc-protobuf:1.10.1'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }
    implementation ('io.grpc:grpc-stub:1.10.1'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }
    implementation ('com.google.api:gax:1.29.0'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }
    implementation ('io.grpc:grpc-okhttp:1.10.1'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }
    implementation ('com.google.photos.library:google-photos-library-client:1.1.0'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }
    implementation 'org.apache.httpcomponents:httpclient-android:4.3.5.1'

**Comment by wmcalyj** [comment]
Thank you!
I tried the following dependencies and it works for me. Although I doubt you need it anymore at this moment :)


  <dependencies>

    <dependency>
      <groupId>com.google.photos.library</groupId>
      <artifactId>google-photos-library-client</artifactId>
      <version>1.1.0</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>api-common</artifactId>
      <version>1.6.0</version>
    </dependency>

    
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>gax-grpc</artifactId>
      <version>1.29.0</version>
    </dependency>

    
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>gax</artifactId>
      <version>1.29.0</version>
    </dependency>

    
    <dependency>
      <groupId>com.google.api.grpc</groupId>
      <artifactId>proto-google-common-protos</artifactId>
      <version>1.12.0</version>
    </dependency>

    
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.5.1</version>
    </dependency>

    
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf</artifactId>
      <version>1.10.1</version>
    </dependency>

    
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-stub</artifactId>
      <version>1.10.1</version>
    </dependency>

    
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.5</version>
    </dependency>

    <dependency>
      <groupId>com.google.api-client</groupId>
      <artifactId>google-api-client</artifactId>
      <version>1.24.1</version>
    </dependency>

    <dependency>
      <groupId>com.google.oauth-client</groupId>
      <artifactId>google-oauth-client-jetty</artifactId>
      <version>1.24.1</version>
    </dependency>

    
    <dependency>
      <groupId>commons-httpclient</groupId>
      <artifactId>commons-httpclient</artifactId>
      <version>3.1</version>
    </dependency>

    
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
      <version>1.10.1</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.23.Final</version>
    </dependency>

**Comment by panovvitalik** [comment]
Exactly :)

Next Your issues when using this library possibly can be: 

https://github.com/google/java-photoslibrary/issues/15
https://github.com/google/java-photoslibrary/issues/11

And these issues I cannot resolve :(

**Comment by hmallepally** [comment]
I found this to be a dependency issue. I have seen this problem and upon investigation, the code is internally trying to load android Application class with class.forName and if successful, it treats it as android and otherwise it is non android.

problem I saw was because some dependency I had android jar into my classpath (google guava android or so) so excluded that dependency and it worked pretty fine.

I think the error message should be improved and give more meaningful message than asking to add grpc-netty, because the error can happen even with grpc-netty in classpath.

**Comment by jfschmakeit** [comment]
@hmallepally Could you share some more details about the dependency issue? It would be great if you can share the exact dependency that's causing the problem. What did you have to exclude? Was this just `grpc-netty`?

(Note that this library is not tested/supported on Android yet. I believe some of our dependencies have Android-specific versions that may help address some of these issues too, otherwise this is something we may have to take further upstream.)

**Comment by DennyWeinberg** [comment]
```
    implementation 'io.grpc:grpc-android:1.28.1'
    implementation 'io.grpc:grpc-okhttp:1.28.1'
```
